//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.WebScrapping.Marvel.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MARVEL
    {
        public int Id { get; set; }
        public string ADICIONADO_IN_MARVEL { get; set; }
        public string RATING { get; set; }
        public string ESCRITOR { get; set; }
        public string ARTISTA_CAPA { get; set; }
        public string DESCRICAO { get; set; }
        public string IMPRECAO { get; set; }
        public string FORMATO { get; set; }
        public string PRECO { get; set; }
        public string IMAGEM { get; set; }
        public Nullable<System.DateTime> DT_ATUALIZACAO { get; set; }
        public string DATA_PUBLICACAO { get; set; }
        public string TITULO { get; set; }
    }
}
