//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minicurso.Webscraping.Project.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVISTINHA
    {
        public int Id { get; set; }
        public string titulo { get; set; }
        public string escritor { get; set; }
        public string desenhista { get; set; }
        public string publicacao { get; set; }
        public string imagem { get; set; }
        public string descricao { get; set; }
    }
}
